# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
music = Music.create([
  {artist: "The Weeknd", song: "King of the fall", genre: "Hip Hop", bio:'Abęl Makkonen Tesfaye (born 16 February 1990), known professionally by his stage name The Weeknd (pronounced "the weekend"), is a Canadian singer, songwriter, and record producer.[1] In late 2010, Tesfaye anonymously uploaded several songs to YouTube under the name "The Weeknd". He released three nine-track mixtapes throughout 2011: House of Balloons, Thursday and Echoes of Silence, which were critically acclaimed.[2] The following year, he released a compilation album Trilogy, thirty tracks consisting of remastered versions of the mixtape material and three additional songs. It was released under Republic Records and his own label XO.', song_url: "https://www.youtube.com/watch?v=ZXBcwyMUrcU"},
  {artist: "Lana Del Ray", song: "Video Games", genre: "Slow Rock", bio:'Elizabeth Woolridge Grant (born June 21, 1985),[1] better known by her stage name Lana Del Rey, is an American singer, songwriter, and model. Born and raised in New York, Del Rey embarked on a music career in 2005 and first received widespread attention in 2011, when the music video for her single "Video Games" became a viral internet sensation.[2] Del Rey received further recognition after her major-label debut Born to Die peaked at number two on the U.S. charts and was the fifth best-selling album of 2012. A remix of its single "Summertime Sadness", produced by Cedric Gervais, peaked at number six on the U.S., and the Paradise EP followed that November, garnering Del Rey her first Grammy nomination for Best Pop Vocal Album. Three of the EPs tracks were featured in her short film Tropico, which premiered in December 2013.', song_url: "https://www.youtube.com/watch?v=cE6wxDqdOV0"},
  {artist: "Halsey", song: "Colors(Stripped)", genre: "Slow Rock", bio:'Ashley Nicolette Frangipane (born September 29, 1994),[1] known by her stage name Halsey /ˈhɔːl.zɪ/,[2] is an American singer and songwriter. She started songwriting at the age of 17. In 2014, she signed her first recording contract with Astralwerks and released her debut EP, titled Room 93. Her debut studio album, Badlands, was released in 2015.', song_url: "https://www.youtube.com/watch?v=YKnjzQv0eyo"},
  {artist: "Kiiara", song: "Feels(Remix)", genre: "Slow Rock", bio:'Kiara Saulters (born 1994 or 1995), mononymously known as Kiiara, is a pop and alternative recording artist from Illinois.[2][3] She is currently signed to Atlantic Records. Her music is described as downcast electronic pop with bass-heavy, trap-style rap production.[4]', song_url: "https://www.youtube.com/watch?v=U9ZO2Px0zww"},
  {artist: "Melanie Martinez", song: "Dollhouse(Remix)", genre: "Slow Rock", bio:'Melanie Adele Martinez (born April 28, 1995)[1][2] is an American singer and songwriter. Melanie Martinez auditioned for the American television vocal talent show The Voice and became a member of Team Adam. Within the fifth week, she was eliminated which subsequently led to her beginning independent work on original material.[3] In 2014, she released Dollhouse, her debut EP featuring the singles "Dollhouse" and "Carousel", which appeared on the trailer for the television series American Horror Story: Freak Show.[4]', song_url: "https://www.youtube.com/watch?v=POEULYAeYAM"},
  {artist: "Kayne West", song: "Blood on the Leaves", genre: "Hip Hop", bio:'Kanye Omari West was born in Atlanta, Georgia, on June 8, 1977. He left college to pursue a musical career, producing tracks for Jay-Z while polishing his demo. He released The College Dropout in 2004. It sold 2.6 million copies and won Best Rap Album', song_url: "https://www.youtube.com/watch?v=7CDIzsOEzN4"},
  {artist: "Drake", song: "Energy", genre: "Hip Hop", bio:'Drake, the worlds only black Jewish-Canadian rap star, was born Aubrey Drake Graham on October 24, 1986, in Toronto, Canada. Drake grew up with music in his blood. His father, Dennis Graham, was a drummer for legendary rock star Jerry Lee Lewis, and Drake says that his mother, Sandi Graham, also hails from a "very musical" family. Drake comes from an eclectic and unique racial and religious background. His father is an African-American Catholic and his mother is a white Canadian Jew. Speaking about his personal identity, Drake says, "At the end of the day, I consider myself a black man because Im more immersed in black culture than any other. Being Jewish is kind of a cool twist. It makes me unique."', song_url: "https://www.youtube.com/watch?v=7LnBvuzjpr4"},
  {artist: "Tyler The Creator", song: "Right Now", genre: "Rap", bio:'Tyler Gregory Okonma[5] (born March 6, 1991), better known by his stage name Tyler, The Creator, is an American rapper, songwriter, record producer, musician, graphic designer, music video director, and actor.[3] Born in Ladera Heights, California, he rose to prominence as the leader and co-founder of the alternative hip hop collective Odd Future and has rapped on and produced songs for nearly every Odd Future release.[6] Okonma also creates all the artwork for the groups releases[2] and said in an interview with radio presenter DJ Semtex, that he designs all the groups clothing and other merchandise as well.[3] After releasing his debut album Goblin under XL Recordings, in April 2011, he signed a joint venture deal for him and his label Odd Future Records, with RED Distribution and Sony Music Entertainment.[7] Following that he released his second studio album Wolf, which was met with generally positive reviews and debuted at number three on the US Billboard 200 selling 90,000 copies in its first week.', song_url: "https://www.youtube.com/watch?v=oCd6SQ67k-Y"}

  ])
